ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyS4 # Pro
# ARDUINO_PORT = /dev/ttyUSB0 # Pro
# ARDUINO_PORT = /dev/ttyACM0  # UNO

ARDUINO_LIBS    = UselessBox UselessBoxSrc UselessBoxModes UselessBoxManager UselessBoxPeripheral Servo
BOARD_TAG = pro5v328
# BOARD_TAG = uno
# BOARD_TAG = mega2560

include /usr/share/arduino/Arduino.mk
